# Generated by Django 3.0.2 on 2020-01-22 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='fffffff', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
