# Generated by Django 3.0.2 on 2020-01-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_auto_20200123_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Nairobi', max_length=100),
            preserve_default=False,
        ),
    ]
