# Generated by Django 3.0.2 on 2020-01-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
